# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/public_suffix/all/public_suffix.rbi
#
# public_suffix-4.0.5

module PublicSuffix
  def self.decompose(name, rule); end
  def self.domain(name, **options); end
  def self.normalize(name); end
  def self.parse(name, list: nil, default_rule: nil, ignore_private: nil); end
  def self.valid?(name, list: nil, default_rule: nil, ignore_private: nil); end
end
