# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/retriable/all/retriable.rbi
#
# retriable-3.1.2

module Retriable
  def config; end
  def configure; end
  def retriable(opts = nil); end
  def self.config; end
  def self.configure; end
  def self.retriable(opts = nil); end
  def self.with_context(context_key, options = nil, &block); end
  def with_context(context_key, options = nil, &block); end
end
